float:
  any:
  - base_args: ['@metric']
    constructor: Oracle
    disabled: false
    docker_tag: ann-benchmarks-oracle
    module: ann_benchmarks.algorithms.oracle
    name: oracle
    run_groups:
      normal:
        arg_groups: [{neighbors: [16, 32, 48], efConstruction: [100, 200], target_accuracy: 95}]
        args: {}
        query_args: [[10, 20, 30, 40, 80, 120, 200]]